### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by filipferris** [Skarbo/hass-scinan-thermostat#9]
I have the Prosmart thermostat. When adding the integration, I get the error "connection reset by peer", here's the log message:

```
Logger: homeassistant.config_entries
Source: config_entries.py:504
First occurred: 15:29:44 (2 occurrences)
Last logged: 15:32:36

Error setting up entry Filip.nicolaisen@outlook.com for scinan_thermostat
Error setting up entry filip.nicolaisen@outlook.com for scinan_thermostat
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 504, in async_setup
    result = await component.async_setup_entry(hass, self)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/scinan_thermostat/__init__.py", line 71, in async_setup_entry
    await scinan_api.authenticate()
  File "/config/custom_components/scinan_thermostat/api/__init__.py", line 158, in authenticate
    data: ScinanLoginResponseData = await self.request(
                                    ^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/scinan_thermostat/api/__init__.py", line 226, in request
    resp = await self.web_session.post(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client.py", line 605, in _request
    await resp.start(conn)
  File "/usr/local/lib/python3.12/site-packages/aiohttp/client_reqrep.py", line 966, in start
    message, payload = await protocol.read()  # type: ignore[union-attr]
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/streams.py", line 622, in read
    await self._waiter
aiohttp.client_exceptions.ClientOSError: [Errno 104] Connection reset by peer
```

**Comment by filipferris** [comment]
After logging out of the app, it seems to work. Seems you can only have one connection running at a time.
